const menu = [
  {
    id: 0,
    type: "toyuq",
    name: "çörək",
    defPrice: 2.0,
    count: 0,
    totalPrice: 2.0,
  },
  {
    id: 1,
    type: "toyuq",
    name: "lavaş",
    defPrice: 2.2,
    count: 0,
    totalPrice: 2.2,
  },
  {
    id: 2,
    type: "toyuq",
    name: "Porsion",
    defPrice: 4.5,
    count: 0,
    totalPrice: 4.5,
  },
  {
    id: 3,
    type: "toyuq",
    name: "Bastırma",
    defPrice: 2.5,
    count: 0,
    totalPrice: 2.5,
  },
  {
    id: 4,
    type: "toyuq",
    name: "Tombili",
    defPrice: 2.5,
    count: 0,
    totalPrice: 2.5,
  },
  {
    id: 5,
    type: "toyuq",
    name: "Sezar",
    defPrice: 3.0,
    count: 0,
    totalPrice: 3.0,
  },
  {
    id: 6,
    type: "toyuq",
    name: "Pilov üstü",
    defPrice: 5.5,
    count: 0,
    totalPrice: 5.5,
  },
  {
    id: 7,
    type: "toyuq",
    name: "My Dönər Roll",
    defPrice: 3.7,
    count: 0,
    totalPrice: 3.7,
  },
  {
    id: 8,
    type: "toyuq",
    name: "Pendirli çörək",
    defPrice: 2.5,
    count: 0,
    totalPrice: 2.5,
  },
  {
    id: 9,
    type: "toyuq",
    name: "Pendirli lavaş",
    defPrice: 2.7,
    count: 0,
    totalPrice: 2.7,
  },
  {
    id: 10,
    type: "toyuq",
    name: "Limuzin çörək",
    defPrice: 3.5,
    count: 0,
    totalPrice: 3.5,
  },
  {
    id: 11,
    type: "toyuq",
    name: "Limuzin lavaş",
    defPrice: 3.7,
    count: 0,
    totalPrice: 3.7,
  },
  {
    id: 12,
    type: "toyuq",
    name: "Şaurma çörək",
    defPrice: 2.7,
    count: 0,
    totalPrice: 2.7,
  },
  {
    id: 13,
    type: "toyuq",
    name: "Şaurma lavaş",
    defPrice: 2.9,
    count: 0,
    totalPrice: 2.9,
  },

  {
    id: 14,
    type: "et",
    name: "çörək",
    defPrice: 2.5,
    count: 0,
    totalPrice: 2.5,
  },
  {
    id: 15,
    type: "et",
    name: "lavaş",
    defPrice: 2.7,
    count: 0,
    totalPrice: 2.7,
  },
  {
    id: 16,
    type: "et",
    name: "Porsion",
    defPrice: 5.5,
    count: 0,
    totalPrice: 5.5,
  },
  {
    id: 17,
    type: "et",
    name: "Bastırma",
    defPrice: 3.0,
    count: 0,
    totalPrice: 3.0,
  },
  {
    id: 18,
    type: "et",
    name: "Tombili",
    defPrice: 3.0,
    count: 0,
    totalPrice: 3.0,
  },
  {
    id: 19,
    type: "et",
    name: "Sezar",
    defPrice: 3.5,
    count: 0,
    totalPrice: 3.5,
  },
  {
    id: 20,
    type: "et",
    name: "Pilov üstü",
    defPrice: 6.5,
    count: 0,
    totalPrice: 6.5,
  },
  {
    id: 21,
    type: "et",
    name: "My Dönər Roll",
    defPrice: 4.7,
    count: 0,
    totalPrice: 4.7,
  },
  {
    id: 22,
    type: "et",
    name: "Pendirli çörək",
    defPrice: 3.0,
    count: 0,
    totalPrice: 3.0,
  },
  {
    id: 23,
    type: "et",
    name: "Pendirli lavaş",
    defPrice: 3.2,
    count: 0,
    totalPrice: 3.2,
  },
  {
    id: 24,
    type: "et",
    name: "Limuzin çörək",
    defPrice: 4.5,
    count: 0,
    totalPrice: 4.5,
  },
  {
    id: 25,
    type: "et",
    name: "Limuzin lavaş",
    defPrice: 4.7,
    count: 0,
    totalPrice: 4.7,
  },
  {
    id: 26,
    type: "et",
    name: "Şaurma çörək",
    defPrice: 3.0,
    count: 0,
    totalPrice: 3.0,
  },
  {
    id: 27,
    type: "et",
    name: "Şaurma lavaş",
    defPrice: 3.2,
    count: 0,
    totalPrice: 3.2,
  },
  {
    id: 28,
    type: "et",
    name: "İskəndər",
    defPrice: 7.9,
    count: 0,
    totalPrice: 7.9,
  },
  {
    id: 29,
    type: "et",
    name: "Mix Dönər",
    defPrice: 2.5,
    count: 0,
    totalPrice: 2.5,
  },

  {
    id: 30,
    type: "burger",
    name: "Toyuq Burger",
    defPrice: 3.5,
    count: 0,
    totalPrice: 3.5,
  },
  {
    id: 31,
    type: "burger",
    name: "Toyuq Cheesburger",
    defPrice: 4.0,
    count: 0,
    totalPrice: 4.0,
  },
  {
    id: 32,
    type: "burger",
    name: "Ət Burger",
    defPrice: 4.5,
    count: 0,
    totalPrice: 4.5,
  },
  {
    id: 33,
    type: "burger",
    name: "Ət Cheesburger",
    defPrice: 5.0,
    count: 0,
    totalPrice: 5.0,
  },

  {
    id: 34,
    type: "sorba",
    name: "Mərci şorbası",
    defPrice: 2.0,
    count: 0,
    totalPrice: 2.0,
  },
  {
    id: 35,
    type: "sorba",
    name: "Günün şorbası",
    defPrice: 2.0,
    count: 0,
    totalPrice: 2.0,
  },

  {
    id: 36,
    type: "salat",
    name: "Çoban salatı",
    defPrice: 2.9,
    count: 0,
    totalPrice: 2.9,
  },
  {
    id: 37,
    type: "salat",
    name: "Sezar salatı",
    defPrice: 6.0,
    count: 0,
    totalPrice: 6.0,
  },
  {
    id: 38,
    type: "salat",
    name: "Paytaxt salatı",
    defPrice: 3.0,
    count: 0,
    totalPrice: 3.0,
  },
  {
    id: 39,
    type: "cigkofte",
    name: "Çiğ Köftə",
    defPrice: 3.0,
    count: 0,
    totalPrice: 3.0,
  },
  {
    id: 40,
    type: "cigkofte",
    name: "Çiğ Köftə servis",
    defPrice: 4.0,
    count: 0,
    totalPrice: 4.0,
  },
  {
    id: 41,
    type: "cigkofte",
    name: "Çiğ Köftə dürüm",
    defPrice: 3.5,
    count: 0,
    totalPrice: 3.5,
  },
  {
    id: 42,
    type: "kofte",
    name: "Toyuq Köftə çörək",
    defPrice: 2.5,
    count: 0,
    totalPrice: 2.5,
  },
  {
    id: 43,
    type: "kofte",
    name: "Toyuq Köftə lavaş",
    defPrice: 2.7,
    count: 0,
    totalPrice: 2.7,
  },
  {
    id: 44,
    type: "kofte",
    name: "Toyuq Köftə pendirli çörək",
    defPrice: 3.0,
    count: 0,
    totalPrice: 3.0,
  },

  {
    id: 45,
    type: "kofte",
    name: "Toyuq Köftə pendirli lavaş",
    defPrice: 3.2,
    count: 0,
    totalPrice: 3.2,
  },
  {
    id: 46,
    type: "kofte",
    name: "Ət Köftə çörək",
    defPrice: 3.0,
    count: 0,
    totalPrice: 3.0,
  },
  {
    id: 47,
    type: "kofte",
    name: "Ət Köftə lavaş",
    defPrice: 3.2,
    count: 0,
    totalPrice: 3.2,
  },
  {
    id: 48,
    type: "kofte",
    name: "Ət Köftə pendirli çörək",
    defPrice: 3.5,
    count: 0,
    totalPrice: 3.5,
  },
  {
    id: 49,
    type: "kofte",
    name: "Ət Köftə pendirli lavaş",
    defPrice: 3.7,
    count: 0,
    totalPrice: 3.7,
  },
  {
    id: 50,
    type: "kofte",
    name: "Toyuq Köftə servis",
    defPrice: 5.0,
    count: 0,
    totalPrice: 5.0,
  },
  {
    id: 51,
    type: "kofte",
    name: "Toyuq Köftə pendirli servis",
    defPrice: 5.5,
    count: 0,
    totalPrice: 5.5,
  },
  {
    id: 52,
    type: "kofte",
    name: "Ət Köftə servis",
    defPrice: 6.5,
    count: 0,
    totalPrice: 6.5,
  },
  {
    id: 52,
    type: "kofte",
    name: "Ət Köftə pendirli servis",
    defPrice: 7.0,
    count: 0,
    totalPrice: 7.0,
  },
  {
    id: 53,
    type: "tost",
    name: "Sadə tost",
    defPrice: 2.0,
    count: 0,
    totalPrice: 2.0,
  },
  {
    id: 54,
    type: "tost",
    name: "Sucuklu pendirli tost",
    defPrice: 3.0,
    count: 0,
    totalPrice: 3.0,
  },
  {
    id: 55,
    type: "tost",
    name: "Qarışıq tost",
    defPrice: 3.5,
    count: 0,
    totalPrice: 3.5,
  },
  {
    id: 56,
    type: "tost",
    name: "Tost menu",
    defPrice: 5.0,
    count: 0,
    totalPrice: 5.0,
  },
  {
    id: 57,
    type: "tost",
    name: "Nugget + fries",
    defPrice: 5.5,
    count: 0,
    totalPrice: 5.5,
  },
  {
    id: 58,
    type: "tost",
    name: "Fries",
    defPrice: 2.5,
    count: 0,
    totalPrice: 2.5,
  },
  {
    id: 59,
    type: "lunch",
    name: "Şorba, pilav üstü toyuq dönər, ayran",
    defPrice: 5.0,
    count: 0,
    totalPrice: 5.0,
  },
  {
    id: 60,
    type: "lunch",
    name: "Şorba, toyuq köftə çörəkdə, ayran",
    defPrice: 4.5,
    count: 0,
    totalPrice: 4.5,
  },
  {
    id: 61,
    type: "lunch",
    name: "Şorba, toyuq köftə servis, ayran",
    defPrice: 5.5,
    count: 0,
    totalPrice: 5.5,
  },
  {
    id: 62,
    type: "lunch",
    name: "Şorba, ət köftə çörəkdə, ayran",
    defPrice: 5.0,
    count: 0,
    totalPrice: 5.0,
  },
  {
    id: 63,
    type: "lunch",
    name: "Şorba, ət köftə servis, ayran",
    defPrice: 6.0,
    count: 0,
    totalPrice: 6.0,
  },
  {
    id: 64,
    type: "set",
    name: "Toyuq burger, fries, 0.3ml cola",
    defPrice: 6.0,
    count: 0,
    totalPrice: 6.0,
  },
  {
    id: 65,
    type: "set",
    name: "Toyuq cheesburger, fries, 0.3ml cola",
    defPrice: 6.5,
    count: 0,
    totalPrice: 6.5,
  },
  {
    id: 66,
    type: "set",
    name: "Ət burger, fries, 0.3ml cola",
    defPrice: 7.0,
    count: 0,
    totalPrice: 7.0,
  },
  {
    id: 67,
    type: "set",
    name: "Ət cheesburger, fries, 0.3ml cola",
    defPrice: 7.5,
    count: 0,
    totalPrice: 7.5,
  },
  {
    id: 68,
    type: "set",
    name: "Barbekü sos",
    defPrice: 0.5,
    count: 0,
    totalPrice: 0.5,
  },
  {
    id: 69,
    type: "icki",
    name: "Cola, fanta, sprite 0.3ml",
    defPrice: 0.9,
    count: 0,
    totalPrice: 0.9,
  },
  {
    id: 70,
    type: "icki",
    name: "Cola 0.5ml",
    defPrice: 1.4,
    count: 0,
    totalPrice: 1.4,
  },
  {
    id: 71,
    type: "icki",
    name: "Ayran",
    defPrice: 0.6,
    count: 0,
    totalPrice: 0.6,
  },
  {
    id: 72,
    type: "icki",
    name: "Ayran ev yapımı",
    defPrice: 0.8,
    count: 0,
    totalPrice: 0.8,
  },
  {
    id: 73,
    type: "icki",
    name: "Akroşka",
    defPrice: 1.0,
    count: 0,
    totalPrice: 1.0,
  },
  {
    id: 74,
    type: "icki",
    name: "Fuse tea",
    defPrice: 1.8,
    count: 0,
    totalPrice: 1.8,
  },
  {
    id: 75,
    type: "icki",
    name: "Meyvə suyu",
    defPrice: 1.0,
    count: 0,
    totalPrice: 1.0,
  },
];

export default menu;
